export default function TermsPage() {
    return (
        <div className="legal-page">
            <h1>Terms of Service</h1>
            <p className="legal-page__updated">Last updated: {"{{ YEAR }}"}</p>

            <section>
                <h2>1. Acceptance of Terms</h2>
                <p>By using {"{{ APP_NAME }}"}, you agree to be bound by these Terms of Service.</p>
            </section>

            <section>
                <h2>2. Description of Service</h2>
                <p>{"{{ APP_NAME }}"} provides AI-powered tools and services. {"{{ APP_DESCRIPTION }}"}</p>
            </section>

            <section>
                <h2>3. User Accounts</h2>
                <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account.</p>
            </section>

            <section>
                <h2>4. Subscription & Billing</h2>
                <p>Paid plans are billed monthly through Stripe. You can cancel anytime via the billing portal. Refunds are handled on a case-by-case basis.</p>
            </section>

            <section>
                <h2>5. AI-Generated Content</h2>
                <p>Content generated by AI models is provided as-is. We do not guarantee the accuracy or completeness of AI-generated content.</p>
            </section>

            <section>
                <h2>6. Termination</h2>
                <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior.</p>
            </section>

            <section>
                <h2>7. Contact</h2>
                <p>For questions about these terms, please contact us at support@example.com.</p>
            </section>
        </div>
    )
}
